class ParkGenerator {
    constructor() {
        this.usParks = [
            { name: "Acadia", state: "ME", year: "1919" },
            { name: "Arches", state: "UT", year: "1971" },
            { name: "Badlands", state: "SD", year: "1978" },
            { name: "Big Bend", state: "TX", year: "1944" },
            { name: "Biscayne", state: "FL", year: "1980" },
            { name: "Black Canyon of the Gunnison", state: "CO", year: "1999" },
            { name: "Bryce Canyon", state: "UT", year: "1928" },
            { name: "Canyonlands", state: "UT", year: "1964" },
            { name: "Capitol Reef", state: "UT", year: "1971" },
            { name: "Carlsbad Caverns", state: "NM", year: "1930" },
            { name: "Channel Islands", state: "CA", year: "1980" },
            { name: "Congaree", state: "SC", year: "2003" },
            { name: "Crater Lake", state: "OR", year: "1902" },
            { name: "Cuyahoga Valley", state: "OH", year: "2000" },
            { name: "Death Valley", state: "CA/NV", year: "1994" },
            { name: "Denali", state: "AK", year: "1917" },
            { name: "Dry Tortugas", state: "FL", year: "1992" },
            { name: "Everglades", state: "FL", year: "1947" },
            { name: "Gates of the Arctic", state: "AK", year: "1980" },
            { name: "Gateway Arch", state: "MO", year: "2018" },
            { name: "Glacier", state: "MT", year: "1910" },
            { name: "Glacier Bay", state: "AK", year: "1980" },
            { name: "Grand Canyon", state: "AZ", year: "1919" },
            { name: "Grand Teton", state: "WY", year: "1929" },
            { name: "Great Basin", state: "NV", year: "1986" },
            { name: "Great Sand Dunes", state: "CO", year: "2004" },
            { name: "Great Smoky Mountains", state: "TN/NC", year: "1934" },
            { name: "Guadalupe Mountains", state: "TX", year: "1966" },
            { name: "Haleakalā", state: "HI", year: "1916" },
            { name: "Hawaiʻi Volcanoes", state: "HI", year: "1916" },
            { name: "Hot Springs", state: "AR", year: "1921" },
            { name: "Indiana Dunes", state: "IN", year: "2019" },
            { name: "Isle Royale", state: "MI", year: "1940" },
            { name: "Joshua Tree", state: "CA", year: "1994" },
            { name: "Katmai", state: "AK", year: "1980" },
            { name: "Kenai Fjords", state: "AK", year: "1980" },
            { name: "Kings Canyon", state: "CA", year: "1940" },
            { name: "Kobuk Valley", state: "AK", year: "1980" },
            { name: "Lake Clark", state: "AK", year: "1980" },
            { name: "Lassen Volcanic", state:
